# build environment
FROM node:19 as build
WORKDIR /app
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
RUN yarn install --silent
RUN yarn global add react-scripts@3.3.1 -g --silent
ENV VITE_API_URL=/api
COPY . /app
RUN yarn run build

# production environment
FROM nginx:1.16.0-alpine
ENV VITE_API_URL=/api
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
CMD ["nginx", "-g", "daemon off;"]
